<?php

return [
    [
        'label' => 'Data Diri',
        'segment' => 'student-profile',
        'icon' => 'fa-user',
        'permission' => 'guest_profile',
        'routes' => [
            ['label' => 'Index', 'route' => 'dashboard.student-profile', 'permission' => 'guest_profile'],
        ],
    ],
    [
        'label' => 'Registrasi',
        'segment' => 'student-registration',
        'icon' => '🔑',
        'permission' => 'student_registration',
        'routes' => [
            ['label' => 'Index', 'route' => 'dashboard.student-registration', 'permission' => 'student_registration'],
        ],
    ],
    [
        'label' => 'Data Gelar',
        'segment' => 'degree-levels',
        'icon' => '🔑',
        'permission' => 'view_degree-levels',
        'routes' => [
            ['label' => 'Index', 'route' => 'dashboard.degree-levels.index', 'permission' => 'view_degree-levels'],
            ['label' => 'Create', 'route' => 'dashboard.degree-levels.create', 'permission' => 'create_degree-levels'],
            ['label' => 'Edit', 'route' => 'dashboard.degree-levels.edit', 'permission' => 'edit_degree-levels'],
            ['label' => 'Delete', 'route' => 'dashboard.degree-levels.destroy', 'permission' => 'delete_degree-levels'],
        ],
    ],
    [
        'label' => 'Data Fakultas',
        'segment' => 'faculties',
        'icon' => '🔑',
        'permission' => 'view_faculties',
        'routes' => [
            ['label' => 'Index', 'route' => 'dashboard.faculties.index', 'permission' => 'view_faculties'],
            ['label' => 'Create', 'route' => 'dashboard.faculties.create', 'permission' => 'create_faculties'],
            ['label' => 'Edit', 'route' => 'dashboard.faculties.edit', 'permission' => 'edit_faculties'],
            ['label' => 'Delete', 'route' => 'dashboard.faculties.destroy', 'permission' => 'delete_faculties'],
        ],
    ],
    [
        'label' => 'Data Dosen',
        'segment' => 'lecturers',
        'icon' => '🔑',
        'permission' => 'view_lecturers',
        'routes' => [
            ['label' => 'Index', 'route' => 'dashboard.lecturers.index', 'permission' => 'view_lecturers'],
            ['label' => 'Create', 'route' => 'dashboard.lecturers.create', 'permission' => 'create_lecturers'],
            ['label' => 'Edit', 'route' => 'dashboard.lecturers.edit', 'permission' => 'edit_lecturers'],
            ['label' => 'Delete', 'route' => 'dashboard.lecturers.destroy', 'permission' => 'delete_lecturers'],
        ],
    ],
    [
        'label' => 'Data Program Studi',
        'segment' => 'study-programs',
        'icon' => '🔑',
        'permission' => 'view_study-programs',
        'routes' => [
            ['label' => 'Index', 'route' => 'dashboard.study-programs.index', 'permission' => 'view_study-programs'],
            ['label' => 'Create', 'route' => 'dashboard.study-programs.create', 'permission' => 'create_study-programs'],
            ['label' => 'Edit', 'route' => 'dashboard.study-programs.edit', 'permission' => 'edit_study-programs'],
            ['label' => 'Delete', 'route' => 'dashboard.study-programs.destroy', 'permission' => 'delete_study-programs'],
        ],
    ],
    [
        'label' => 'Data Semester',
        'segment' => 'semesters',
        'icon' => '🔑',
        'permission' => 'view_semesters',
        'routes' => [
            ['label' => 'Index', 'route' => 'dashboard.semesters.index', 'permission' => 'view_semesters'],
            ['label' => 'Create', 'route' => 'dashboard.semesters.create', 'permission' => 'create_semesters'],
            ['label' => 'Edit', 'route' => 'dashboard.semesters.edit', 'permission' => 'edit_semesters'],
            ['label' => 'Delete', 'route' => 'dashboard.semesters.destroy', 'permission' => 'delete_semesters'],
        ],
    ],
    [
        'label' => 'Data Semester Akademik',
        'segment' => 'academic-semesters',
        'icon' => '🔑',
        'permission' => 'view_academic-semesters',
        'routes' => [
            ['label' => 'Index', 'route' => 'dashboard.academic-semesters.index', 'permission' => 'view_academic-semesters'],
            ['label' => 'Create', 'route' => 'dashboard.academic-semesters.create', 'permission' => 'create_academic-semesters'],
            ['label' => 'Edit', 'route' => 'dashboard.academic-semesters.edit', 'permission' => 'edit_academic-semesters'],
            ['label' => 'Delete', 'route' => 'dashboard.academic-semesters.destroy', 'permission' => 'delete_academic-semesters'],
        ],
    ],
    [
        'label' => 'Data Mata Kuliah',
        'segment' => 'courses',
        'icon' => '🔑',
        'permission' => 'view_courses',
        'routes' => [
            ['label' => 'Index', 'route' => 'dashboard.courses.index', 'permission' => 'view_courses'],
            ['label' => 'Create', 'route' => 'dashboard.courses.create', 'permission' => 'create_courses'],
            ['label' => 'Edit', 'route' => 'dashboard.courses.edit', 'permission' => 'edit_courses'],
            ['label' => 'Delete', 'route' => 'dashboard.courses.destroy', 'permission' => 'delete_courses'],
        ],
    ],
    [
        'label' => 'Data Kurikulum',
        'segment' => 'curriculums',
        'icon' => '🔑',
        'permission' => 'view_curriculums',
        'routes' => [
            ['label' => 'Index', 'route' => 'dashboard.curriculums.index', 'permission' => 'view_curriculums'],
            ['label' => 'Create', 'route' => 'dashboard.curriculums.create', 'permission' => 'create_curriculums'],
            ['label' => 'Edit', 'route' => 'dashboard.curriculums.edit', 'permission' => 'edit_curriculums'],
            ['label' => 'Delete', 'route' => 'dashboard.curriculums.destroy', 'permission' => 'delete_curriculums'],
        ],
    ],
    [
        'label' => 'Data Gedung Kampus',
        'segment' => 'buildings',
        'icon' => '🔑',
        'permission' => 'view_buildings',
        'routes' => [
            ['label' => 'Index', 'route' => 'dashboard.buildings.index', 'permission' => 'view_buildings'],
            ['label' => 'Create', 'route' => 'dashboard.buildings.create', 'permission' => 'create_buildings'],
            ['label' => 'Edit', 'route' => 'dashboard.buildings.edit', 'permission' => 'edit_buildings'],
            ['label' => 'Delete', 'route' => 'dashboard.buildings.destroy', 'permission' => 'delete_buildings'],
        ],
    ],
    [
        'label' => 'Data Ruang Kelas',
        'segment' => 'rooms',
        'icon' => '🔑',
        'permission' => 'view_rooms',
        'routes' => [
            ['label' => 'Index', 'route' => 'dashboard.rooms.index', 'permission' => 'view_rooms'],
            ['label' => 'Create', 'route' => 'dashboard.rooms.create', 'permission' => 'create_rooms'],
            ['label' => 'Edit', 'route' => 'dashboard.rooms.edit', 'permission' => 'edit_rooms'],
            ['label' => 'Delete', 'route' => 'dashboard.rooms.destroy', 'permission' => 'delete_rooms'],
        ],
    ],
    [
        'label' => 'Data Role',
        'segment' => 'roles',
        'icon' => '🔑',
        'permission' => 'view_roles',
        'routes' => [
            ['label' => 'Index', 'route' => 'dashboard.roles.index', 'permission' => 'view_roles'],
            ['label' => 'Create', 'route' => 'dashboard.roles.create', 'permission' => 'create_roles'],
            ['label' => 'Edit', 'route' => 'dashboard.roles.edit', 'permission' => 'edit_roles'],
            ['label' => 'Delete', 'route' => 'dashboard.roles.destroy', 'permission' => 'delete_roles'],
        ],
    ],
    [
        'label' => 'Data Kelas',
        'segment' => 'classes',
        'icon' => '🔑',
        'permission' => 'view_classes',
        'routes' => [
            ['label' => 'Index', 'route' => 'dashboard.classes.index', 'permission' => 'view_classes'],
            ['label' => 'Create', 'route' => 'dashboard.classes.create', 'permission' => 'create_classes'],
            ['label' => 'Edit', 'route' => 'dashboard.classes.edit', 'permission' => 'edit_classes'],
            ['label' => 'Delete', 'route' => 'dashboard.classes.destroy', 'permission' => 'delete_classes'],
        ],
    ],
    [
        'label' => 'Data Jadwal Mingguan',
        'segment' => 'weekly-schedules',
        'icon' => '🔑',
        'permission' => 'view_weekly-schedules',
        'routes' => [
            ['label' => 'Index', 'route' => 'dashboard.weekly-schedules.index', 'permission' => 'view_weekly-schedules'],
            ['label' => 'Create', 'route' => 'dashboard.weekly-schedules.create', 'permission' => 'create_weekly-schedules'],
            ['label' => 'Edit', 'route' => 'dashboard.weekly-schedules.edit', 'permission' => 'edit_weekly-schedules'],
            ['label' => 'Delete', 'route' => 'dashboard.weekly-schedules.destroy', 'permission' => 'delete_weekly-schedules'],
        ],
    ],
    [
        'label' => 'Data Permission',
        'segment' => 'permissions',
        'icon' => '🔑',
        'permission' => 'view_permissions',
        'routes' => [
            ['label' => 'Index', 'route' => 'dashboard.permissions.index', 'permission' => 'view_permissions'],
            ['label' => 'Create', 'route' => 'dashboard.permissions.create', 'permission' => 'create_permissions'],
            ['label' => 'Edit', 'route' => 'dashboard.permissions.edit', 'permission' => 'edit_permissions'],
            ['label' => 'Delete', 'route' => 'dashboard.permissions.destroy', 'permission' => 'delete_permissions'],
        ],
    ],
    [
        'label' => 'Jadwal Kuliah',
        'segment' => 'student-weekly-schedules',
        'icon' => '🔑',
        'permission' => 'view_student-weekly-schedules',
        'routes' => [
            ['label' => 'Index', 'route' => 'dashboard.student-weekly-schedules.index', 'permission' => 'view_student-weekly-schedules'],
        ],
    ],
    [
        'label' => 'Jadwal Mengajar',
        'segment' => 'lecturer-weekly-schedules',
        'icon' => '🔑',
        'permission' => 'view_lecturer-weekly-schedules',
        'routes' => [
            ['label' => 'Index', 'route' => 'dashboard.lecturer-weekly-schedules.index', 'permission' => 'view_lecturer-weekly-schedules'],
        ],
    ],
    [
        'label' => 'Data Kandidat',
        'segment' => 'student-candidates',
        'icon' => '🔑',
        'permission' => 'view_student-candidates',
        'routes' => [
            ['label' => 'Index', 'route' => 'dashboard.student-candidates.index', 'permission' => 'view_student-candidates'],
            ['label' => 'Show', 'route' => 'dashboard.student-candidates.show', 'permission' => 'show_student-candidates'],
            ['label' => 'Accept-form', 'route' => 'dashboard.student-candidates.accept-form', 'permission' => 'accept-form_student-candidates'],
            ['label' => 'Decline', 'route' => 'dashboard.student-candidates.decline', 'permission' => 'decline_student-candidates'],
        ],
    ],
];
